version: '3'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./noshow.ipynb:/app/noshow.ipynb
      - ./kaggle/input/noshowappointments:/app/kaggle/input/noshowappointments
